; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.5.0-STM32+1 on Wed Jun 04 2025 13:49:46 GMT-0600 (Mountain Daylight Time)
; Wait for set temperatures to be reached
M116 P0

